default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: enhancedsqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
  replica_url: <%= ENV['TURSO_DATABASE_URL'] %>
  replica_token: <%= ENV['TURSO_AUTH_TOKEN'] %>
  sync_interval: 5
